-- White-listed SQL template reference.
-- The app builds WHERE clauses only from config/filter_mapping.yaml and uses bound parameters.
-- Keep SELECT formulas controlled by BI/Data owner.
SELECT
    date_order,
    main_ir AS main_ir,
    order_name AS order_id,
    ir,
    sku,
    follower,
    market_place,
    SUM(price_subtotal) AS gross_sales,
    ABS(SUM(promotion)) AS promo_cost,
    SUM(price_subtotal - ABS(promotion)) AS sales,
    SUM(units) AS units,
    SUM(product_cost_unit) AS product_cost_unit,
    SUM(hardware_cost) AS hardware_cost,
    SUM(removed_hardware) AS removed_hardware,
    SUM(product_cost_unit + hardware_cost - removed_hardware) AS unit_cost,
    SUM(commission) AS commission,
    SUM(ad_spend) AS ad_spend,
    SUM(shipping_fee) AS shipping_fee
FROM bi.ba_mv_profit_order_line_and_ad_info
WHERE
    date_order >= TO_TIMESTAMP(:start_date, 'YYYY-MM-DD HH24:MI:SS')
    AND date_order < TO_TIMESTAMP(:end_date, 'YYYY-MM-DD HH24:MI:SS')
    AND type = :fixed_type
    -- dynamic filter clauses are generated by app from whitelist mapping
GROUP BY main_ir, date_order, ir, order_name, sku, follower, market_place
ORDER BY ir, date_order DESC
LIMIT :max_rows;
